### ISSUE TITLE
Add react native mercadopago into working app

### ISSUE THREAD

**Issue by stescovich-uade** [AlissonAp/ReactNativePrototipoPagamento#3]
Oi:

@AlissonAp Tudo bom? Disculpa si meu portugueis nao e o melhor... To procurando adicionar a opçao mercado pago em uma app React Native. Ainda nao comprei a app, porque nao sei si es posivel a integraçao. Pode me confirmar se voce poderia me ajudar a integrar o pagamento em esta app?

Acho, que si voce pode conseguir adicionar a opçao do mercado pago em esa app, vai conseguir mais cliente que tein interes e pode fazer um negocio muito interesante.

O link da app:
https://codecanyon.net/item/beostore-complete-react-native-template-for-ecommerce/17010642

Muito Obg,
Pablo

**Comment by AlissonAp** [comment]
Boa noite,

No momento estou trabalhando em outros projetos e  infelizmente estou sem tempo para tratar desta questão. De qualquer forma o repositório é público então fique a vontade para realizar uma cópia e realizar alterações que você ache necessário. Acredito que seja possível sim integrar com esse aplicativo que você comenta, porém teria que fazer um teste. 

Att, Alisson Allebrandt
